name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Find Last Tag
        id: last
        uses: jimschubert/query-tag-action@v2
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: 'HEAD~'
          skip-unshallow: 'true'

      - name: Find Current Tag
        id: current
        uses: jimschubert/query-tag-action@v2
        with:
          include: 'v*'
          exclude: '*-rc*'
          commit-ish: '@'
          skip-unshallow: 'true'

      - name: Create Changelog
        id: changelog
        run: |
          echo "## Changelog" > .github/CHANGELOG.md
          git log --pretty=format:"* %s (%h)" ${{steps.last.outputs.tag}}..${{steps.current.outputs.tag}} >> .github/CHANGELOG.md

      - name: View Changelog
        run: cat .github/CHANGELOG.md

      - name: Validates GO releaser config
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: check

      - name: Create release on GitHub
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release --clean --release-notes .github/CHANGELOG.md

