package web

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

const testRuleTimeout = 15 * time.Second

type testRuleRequest struct {
	Name   string `json:"name"`
	Source string `json:"source"`
}

type testRuleResponse struct {
	OK     bool   `json:"ok"`
	Output string `json:"output"`
	Error  string `json:"error,omitempty"`
}

// handleTestRule runs the rule the operator is editing through a dry-run of
// the driplane binary, in a throwaway copy of the rules directory, so the
// running daemon's own rules are never touched. The whole directory is
// copied (not just the one rule) because rules can reference each other
// through #import and @rule, and a single-file copy would report failures
// that do not actually exist.
//
// The only caller-controlled values that reach exec.CommandContext are the
// temp directory path generated by this handler and the daemon's own config
// file path; the rule name only selects a filename inside the temp dir
// (validated through the Store) and the rule source is written to a file,
// neither ever appears on the subprocess command line.
func (s *Server) handleTestRule(w http.ResponseWriter, r *http.Request) {
	// Bound how many dry-run subprocesses can run at once (see testRuleSlots).
	// Rejecting outright rather than queueing means the operator finds out
	// immediately, instead of a pile of requests silently waiting.
	select {
	case s.testSlots <- struct{}{}:
		defer func() { <-s.testSlots }()
	default:
		writeJSON(w, http.StatusServiceUnavailable, testRuleResponse{OK: false, Error: "a rule test is already running, try again in a moment"})
		return
	}

	var req testRuleRequest
	if err := decodeBody(r, &req); err != nil {
		writeError(w, http.StatusBadRequest, err)
		return
	}

	// Validate the name using the same rules the store applies when writing
	// files. The rule under test may not have been saved yet, so ErrNotFound
	// alone must not block the run; any other error (bad path, bad
	// extension, ...) means the name itself is invalid and must not reach
	// the filesystem or the subprocess.
	if _, _, err := s.opts.Store.Read(KindRules, req.Name); err != nil && !errors.Is(err, ErrNotFound) {
		writeStoreError(w, err)
		return
	}

	root, err := s.opts.Store.Root(KindRules)
	if err != nil {
		writeStoreError(w, err)
		return
	}

	tmp, err := os.MkdirTemp("", "driplane-test-*")
	if err != nil {
		writeError(w, http.StatusInternalServerError, err)
		return
	}
	defer os.RemoveAll(tmp)

	if err := copyRuleDir(root, tmp); err != nil {
		writeError(w, http.StatusInternalServerError, err)
		return
	}
	if err := os.WriteFile(filepath.Join(tmp, filepath.Base(req.Name)), []byte(req.Source), 0644); err != nil {
		writeError(w, http.StatusInternalServerError, err)
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), testRuleTimeout)
	defer cancel()

	args := []string{"-dry-run", "-rules", tmp}
	if cfg := s.configFilePath(); cfg != "" {
		args = append(args, "-config", cfg)
	}

	cmd := exec.CommandContext(ctx, s.opts.Executable, args...)
	// The context kills the direct child on timeout, but with WaitDelay at
	// its zero value Wait() would keep reading the output pipes until EOF,
	// which might not arrive until an orphaned grandchild also closes them.
	// Bound that wait so a wedged subprocess cannot also wedge this
	// goroutine and, with it, the deferred os.RemoveAll(tmp) above.
	cmd.WaitDelay = 5 * time.Second
	out, err := cmd.CombinedOutput()

	resp := testRuleResponse{OK: err == nil, Output: string(out)}
	if err != nil {
		resp.Error = err.Error()
		if ctx.Err() != nil {
			resp.Error = fmt.Sprintf("dry-run timed out after %s", testRuleTimeout)
		}
	}
	writeJSON(w, http.StatusOK, resp)
}

// configFilePath returns the config file the running daemon was started
// with, or "" when there is no supervisor (e.g. in tests).
func (s *Server) configFilePath() string {
	if s.opts.Supervisor == nil {
		return ""
	}
	return s.opts.Supervisor.Config().FilePath
}

// copyRuleDir copies the flat *.rule files from src into dst so a dry-run
// subprocess sees the whole rule set, including files the tested rule may
// #import or reference via @rule. Copies always land at 0644 regardless of
// the source file's mode: nothing on this path reads mode bits (the rules
// loader only reads file content) and preserving the original mode would add
// complexity for no observable benefit.
func copyRuleDir(src, dst string) error {
	entries, err := os.ReadDir(src)
	if err != nil {
		return err
	}

	for _, e := range entries {
		if e.IsDir() || !strings.EqualFold(filepath.Ext(e.Name()), ".rule") {
			continue
		}
		content, err := os.ReadFile(filepath.Join(src, e.Name()))
		if err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(dst, e.Name()), content, 0644); err != nil {
			return err
		}
	}
	return nil
}
